env:
  TERM: xterm-256color

window:
  opacity: 0.8
  
  dimensions:
    # columns: 0
    # lines: 0
    columns: 100
    lines: 30
  
  padding:
    x: 10
    y: 10

  title: Alacritty

  class:
    instance: Alacritty
    general: Alacritty

scrolling:
  history: 5008

font:
  normal:
    family: Iosevka
    style: Medium

  bold:
    family: Iosevka
    style: Bold

  italic:
    family:  Iosevka
    style: Medium Italic

  bold_italic:
    family: Iosevka
    style: Bold Italic

  size: 12

  offset:
    x: -1
    y: 1

draw_bold_text_with_bright_colors: true

cursor:
  # Values for `style`:
  #   - ▇ Block
  #   - _ Underline
  #   - | Beam
  style: Block

  unfocused_hollow: true
  vi_mode_style: Underline

import:
  - /home/cafo/.config/alacritty/ashes.yml


key_bindings:
  - { key: V,        mods: Control|Shift, action: Paste            }
  - { key: C,        mods: Control|Shift, action: Copy             }
  - { key: Insert,   mods: Shift,         action: PasteSelection   }
  - { key: Key0,     mods: Control,       action: ResetFontSize    }
  - { key: Equals,   mods: Control,       action: IncreaseFontSize }
  - { key: Plus,     mods: Control,       action: IncreaseFontSize }
  - { key: Minus,    mods: Control,       action: DecreaseFontSize }
  - { key: Minus,    mods: Control,       action: DecreaseFontSize }

  - { key: Paste,                    action: Paste                            }
  - { key: Copy,                     action: Copy                             }
  - { key: L,         mods: Control, action: ClearLogNotice                   }
  - { key: L,         mods: Control, chars: "\x0c"                            }
  - { key: PageUp,    mods: Shift,   action: ScrollPageUp,   mode: ~Alt       }
  - { key: PageDown,  mods: Shift,   action: ScrollPageDown, mode: ~Alt       }
  - { key: Home,      mods: Shift,   action: ScrollToTop,    mode: ~Alt       }
  - { key: End,       mods: Shift,    action: ScrollToBottom   }
