[colors.primary]
background = "#1c2023"
foreground = "#c7ccd1"
dim_foreground = "#CDD6F4"
bright_foreground = "#CDD6F4"

[colors.cursor]
text = "#1c2023"
cursor = "#c7ae95"

[colors.vi_mode_cursor]
text = "#1c2023"
cursor = "#c795ae"


[colors.normal]
black = "#1c2023"
red = "#c7ae95"
green = "#95c7ae"
yellow = "#aec795"
blue = "#ae95c7"
magenta = "#c795ae"
cyan = "#95aec7"
white = "#c7ccd1"

[colors.bright]
black = "#5b6078"
red = "#c7ae95"
green = "#95c7ae"
yellow = "#aec795"
blue = "#ae95c7"
magenta = "#c795ae"
cyan = "#95aec7"
white = "#f3f4f5"
