colors:
  # Default colors
  primary:
    background: '#151515'
    foreground: '#E8E3E3'

  # Normal colors
  normal:
    black:   '#151515'
    red: "#c7ae95"
    green: "#95c7ae"
    yellow: "#aec795"
    blue: "#ae95c7"
    magenta: "#c795ae"
    cyan: "#95aec7"
    white: "#c7ccd1"
  # Bright colors
  bright:
    black:   '#424242'
    red: "#c7ae95"
    green: "#95c7ae"
    yellow: "#aec795"
    blue: "#ae95c7"
    magenta: "#c795ae"
    cyan: "#95aec7"
    white: "#f3f4f5"
