[colors.normal]
black = "0xf2ecbc"
red = "0xc84053"
green = "0x6f894e"
yellow = "0x77713f"
magenta = "0x4d699b"
blue = "0xb35b79"
cyan = "0x597b75"
white = "0x545464"

[colors.bright]
black = "0xa6a69c"
red = "0xc84053"
green = "0x6f894e"
yellow = "0x77713f"
magenta = "0x4d699b"
blue = "0xb35b79"
cyan = "0x597b75"
white = "0x545464"

[colors.primary]
background = "0xf2ecbc"
foreground = "0x545464"
