[colors.normal]
black = "0x26292c"
red = "0xFF6188"
green = "0xA9DC76"
yellow = "0xFFD866"
magenta = "0xAB9DF2"
blue = "0xFC9867"
cyan = "0x78DCE8"
white = "0xFCFCFA"

[colors.bright]
black = "0x727072"
red = "0xFF6188"
green = "0xA9DC76"
yellow = "0xFFD866"
magenta = "0xAB9DF2"
blue = "0xFC9867"
cyan = "0x78DCE8"
white = "0xFCFCFA"

[colors.primary]
background = "0x26292c"
foreground = "0xFCFCFA"
