[colors.bright]
black = "0x525252"
blue = "0x78a9ff"
cyan = "0x82cfff"
green = "0x42be65"
magenta = "0xbe95ff"
red = "0xff7eb6"
white = "0x858893"
yellow = "0xf1fa8c"

[colors.normal]
black = "0x161616"
blue = "0x78a9ff"
cyan = "0x82cfff"
green = "0x42be65"
magenta = "0xbe95ff"
red = "0xff7eb6"
white = "0xd0d0d0"
yellow = "0xf1fa8c"

[colors.primary]
background = "0x161616"
foreground = "0xd0d0d0"
