# name: ROSEPRIME colors for Alacritty
# url: https://github.com/alacritty/alacritty
# upstream: https://github.com/cdmill/neomodern.nvim/raw/main/extras/alacritty/roseprime.toml
# author: Casey Miller

# Default colors
[colors.primary]
background = '#121315'
# alternate, darker background = '#111111'
foreground = '#adadcc'

#[colors.cursor]
#cursor = '#adadcc'
#text = '#121315'

# Normal colors
[colors.normal]
black = '#121315'
red = '#ba5f60'
green = '#647977'
yellow = '#c4959c'
blue = '#6172A0'
magenta = '#6C6B9B'
cyan = '#436285'
white = '#6F6F83'

# Bright colors
[colors.bright]
black = '#666a82'
red = '#ad82a2'
green = '#9bbdb8'
yellow = '#d2af98'
blue = '#95b1fc'
magenta = '#a8a6f5'
cyan = '#6397cf'
white = '#adadcc'

# Indexed Colors
[[colors.indexed_colors]]
index = 16
color = '#111111'

[[colors.indexed_colors]]
index = 17
color = '#a8a6f5'
