[ids]
*
overload_tap_timeout = 10

[main]
insert = home
capslock = overload(control, esc)
# lettermod(layer, key, idle_timeout, hold_timeout)
# If you typed another key <150ms ago, it types the letter (no mod).
# If you've been idle for >150ms and hold for >200ms, it acts as a mod.
a = lettermod(shift, a, 150, 200)
s = lettermod(alt, s, 150, 200)
d = lettermod(meta, d, 150, 200)
j = lettermod(meta, j, 150, 200)
k = lettermod(alt, k, 150, 200)
l = lettermod(shift, l, 150, 200)
f = lettermod(control, f, 150, 200)
h = lettermod(control, h, 150, 200)
