#!/usr/bin/env python3
from time import sleep
from subprocess import run
p1=run(
    ['dunstctl','is-paused'],
    capture_output=True,
    text=True,
)
x=p1.stdout.strip()

if x=='true':
    run('dunstctl set-paused false', shell=True)
    run("notify-send 'Notifications back on'", shell=True)
elif x=='false':
    run("notify-send 'Notifications off'", shell=True)
    sleep(1)
    run('dunstctl set-paused true', shell=True)
