#!/usr/bin/env python3
import subprocess
import os
from tkinter import *
from PIL import ImageTk, Image

root=Tk()
root.title("Wallpaper")
root.configure(background="#282a36")
root.geometry("1100x700")
text='\n Wallpapers \n\n'

y=subprocess.Popen('echo $HOME', shell=True, stdout=subprocess.PIPE)
out=y.communicate()[0].decode().strip()+'/'
if os.path.exists(out+".wall"):
    pass
else:
    os.mkdir(out+".wall")

def get_directory():
    global x
    global dire
    global text
    text='\n Wallpapers \n\n'
    dire=e1.get()
    fil=out+'.dire.txt'
    if os.path.exists(out+'.dire.txt') and dire=='':
        with open(fil) as r:
            dire=r.read().strip()
            x=os.listdir(dire)
        for i, j in enumerate(x, start=1):
            text+="    "+str(i)+") "+j+"\n"
        L2 = Label(root,text='',bg="#282a36",justify="left",anchor="nw", font=("space mono for powerline",12))
        L2.place(x=140,y=275,height=30,width=300)
        None
    else:
        if os.path.exists(dire) or os.path.exists(out+dire):
            if dire.split('/')[1]=='home':
                with open(fil,'w') as f:
                    f.write(dire)
                x=os.listdir(dire)
            else:
                with open(fil,'w') as f:
                    f.write(out+dire)
                x=os.listdir(out+dire)
                for i, j in enumerate(x, start=1):
                    text+="    "+str(i)+") "+j+"\n"
            L2 = Label(root,text='',bg="#282a36",justify="left",anchor="nw", font=("space mono for powerline",12))
            L2.place(x=140,y=275,height=30,width=300)
        else:
            L2 = Label(root,text='Directory does not exist',bg="#f1fa8c",justify="left",anchor="nw", font=("space mono for powerline",12))
            L2.place(x=140,y=275,height=30,width=300)

    L1 = Label(root,text=text,bg="#f1fa8c",fg="#000000",justify="left",anchor="nw", font=("space mono for powerline",12))
    L1.place(x=600,y=0,height=4000,width=4000)

def set_wallpaper(a):
    global image
    wallpaper=e2.get()
    if wallpaper.isdigit():
        if int(wallpaper)<=len(x):
            setwal=x[int(wallpaper)-1]
            pic=dire+'/'+setwal
            if a==1:
                cmd='feh --bg-scale '+pic
                subprocess.call(cmd, shell=True)
            elif a==2:
                new=out+'.wall/img.png'
                cmd='convert '+pic+' -resize 480x270 '+new
                subprocess.call(cmd, shell=True)
                canvas=Canvas(root, width=480, height=270, bg="#282a36")
                canvas.place(x=55,y=320,height=270,width=480)
                image=ImageTk.PhotoImage(Image.open(new))
                canvas.create_image(0, 0, anchor=NW, image=image)


            L2 = Label(root,text='',bg="#282a36",justify="left",anchor="nw", font=("space mono for powerline",12))
            L2.place(x=140,y=275,height=30,width=300)
        else:
            L2 = Label(root,text='Invalid Input',fg="#000000",bg="#f1fa8c",justify="left",anchor="nw", font=("space mono for powerline",12))
            L2.place(x=140,y=275,height=30,width=300)
            label=Label(root, bg="#282a36", text='')
            label.place(x=55,y=320,height=270,width=480)
    else:
        label=Label(root, bg="#282a36", text='')
        label.place(x=55,y=320,height=270,width=480)
        L2 = Label(root,text='Please Enter Index Number',bg="#f1fa8c",justify="left",anchor="nw", font=("space mono for powerline",12))
        L2.place(x=140,y=275,height=30,width=300)


e1=Entry(root,bg="#aaeedd", fg="#000000", font=("space mono for powerline", 12))
e2=Entry(root,bg="#aaeedd", fg="#000000", font=("space mono for powerline", 12))
b1=Button(root,bg="#FF7696", fg="#000000", font=("space mono for powerline", 12), command=get_directory, text="Set Directory")
b2=Button(root,bg="#FF7696", fg="#000000", font=("space mono for powerline", 12), text="Set Wallpaper", command=lambda:set_wallpaper(1))
b3=Button(root,bg="#FF7696", fg="#000000", font=("space mono for powerline", 12), text="Preview", command=lambda:set_wallpaper(2))
L1 = Label(root,text=text,bg="#f1fa8c", fg="#000000",justify="left",anchor="nw", font=("space mono for powerline",12))

e1.place(x=140, y=105, height=30, width=300)
b1.place(x=220, y=145, height=30, width=145)
e2.place(x=140, y=185, height=30, width=300)
b2.place(x=140, y=225, height=30, width=145)
b3.place(x=295, y=225, height=30, width=145)
L1.place(x=600,y=0,height=4000,width=4000)


root.mainloop()
