#!/usr/bin/env python3

themes = {
    "everforest": {
        "zero": "#83b6af",
        "black": "#323d43",
        "red": "#e68183",
        "green": "#a7c080",
        "yellow": "#dbbc7f",
        "magenta": "#d699b6",
        "violet": "#a292a3",
        "blue": "#7fbbb3",
        "teal": "#83c092",
    },
    "kanagawa_lotus": {
        "zero": "#83b6af",
        "black": "#f2ecbc",
        "red": "#c84053",
        "green": "#6f894e",
        "yellow": "#77713f",
        "magenta": "#b35b79",
        "violet": "#a292a3",
        "blue": "#4d699b",
        "teal": "#597b75",
        },
    "kanagawa": {
        "zero": "#83b6af",
        "black": "#181616",
        "red": "#c4746e",
        "green": "#8a9a7b",
        "yellow": "#c4b28a",
        "magenta": "#d7beda",
        "violet": "#a292a3",
        "blue": "#8ba4b0",
        "teal": "#AEC795",
        },
    "oxocarbon": {
        "zero": "#83b6af",
        "black": "#161616",
        "red": "#ff7eb6",
        "green": "#42be65",
        "yellow": "#f1fa8c",
        "magenta": "#d7beda",
        "violet": "#be95ff",
        "blue": "#78A9FF",
        "teal": "#AEC795",
    },
    "levuaska": {
        "zero": "#83b6af",
        "black": "#0f0f17",
        "red": "#d78787",
        "green": "#afbea2",
        "yellow": "#e4c9af",
        "magenta": "#d7beda",
        "violet": "#ae95c7",
        "blue": "#a1bdce",
        "teal": "#AEC795",
    },
    "ashes": {
        "zero": "#83b6af",
        "black": "#1c2023",
        "red": "#c79595",
        "green": "#95c7ae",
        "yellow": "#c7c795",
        "magenta": "#c795ae",
        "violet": "#ae95c7",
        "blue": "#95aec7",
        "teal": "#AEC795",
    },
    "palenight": {
        "zero": "#D8DEE9",
        "black": "#292d3e",
        "red": "#ff8b92",
        "green": "#c3e88d",
        "yellow": "#ffe585",
        "magenta": "#f5c2e7",
        "violet": "#c792ea",
        "blue": "#82aaff",
        "teal": "#81a1c1",
        },
    "frappe": {
            "zero": "#D8DEE9",
            "black": "#303446",
            "red": "#e78284",
            "green": "#a6d189",
            "yellow": "#e5c890",
            "magenta": "#eebebe",
            "violet": "#ca9ee6",
            "blue": "#8caaee",
            "teal": "#babbf1",
            },
    "macchiato": {
            "zero": "#D8DEE9",
            "black": "#24273a",
            "red": "#ed8796",
            "green": "#a6da95",
            "yellow": "#eed49f",
            "magenta": "#f0c6c6",
            "violet": "#c6a0f6",
            "blue": "#8aadf4",
            "teal": "#b7bdf8",
            },
    "docha": {
            "zero": "#D8DEE9",
            "black": "#282a36",
            "red": "#f38baf",
            "green": "#a6ebaf",
            "yellow": "#f9e2af",
            "magenta": "#f2cdcd",
            "violet": "#cba6f7",
            "blue": "#96CDFB",
            "teal": "#c9cbff",
            },
    "mocha": {
            "zero": "#D8DEE9",
            "black": "#1e1e2e",
            "red": "#f38baf",
            "green": "#a6ebaf",
            "yellow": "#f9e2af",
            "magenta": "#f2cdcd",
            "violet": "#cba6f7",
            "blue": "#96CDFB",
            "teal": "#c9cbff",
            },
    "dracula": {
            "zero": "#D8DEE9",
            "black": "#282a36",
            "red": "#ff6e6e",
            "green": "#50fa7b",
            "yellow": "#f1fa8c",
            "magenta": "#ff79c6",
            "blue": "#d6acff",
            "violet": "#8be9fd",
            "teal": "#afffff",
            },
    "one": {
            "zero": "#c8ccd4",
            "black": "#282c34",
            "red": "#e06c75",
            "green": "#98c379",
            "yellow": "#e5c07b",
            "magenta": "#f5c2e7",
            "violet": "#c678dd",
            "blue": "#61afef",
            "teal": "#56b6c2",
            },
    "nord": {
            "zero": "#D8DEE9",
            "black": "#2e3440",
            "red": "#bf616a",
            "green": "#a3be8c",
            "yellow": "#ebcb8b",
            "magenta": "#b48ead",
            "violet": "#d6acff",
            "blue": "#b5e8e0",
            "teal": "#81a1c1",
            },
    "latte": {
            "zero": "#4c4f69",
            "black": "#eff1f5",
            "red": "#d20f39",
            "green": "#40a02b",
            "yellow": "#df8e1d",
            "magenta": "#ea76cb",
            "violet": "#8839ef",
            "blue": "#1e66f5",
            "teal": "#179299",
            }
    }
