## name: Alabaster Dark
## author: Nikita Prokopov
## license: MIT
## upstream: https://raw.githubusercontent.com/anmolmathias/kitty-alabaster/master/alabaster-dark.conf
## blurb: A dark color scheme adapted from Alabaster for the kitty terminal.

#: The basic colors

foreground              #bdc4a7
background              #0c0c0c

selection_foreground    #cecece
selection_background    #293334


#: Cursor colors

cursor                  #da627d
cursor_text_color       #000000


#: URL underline color when hovering with mouse

url_color               #cd974b


#: The basic 16 colors

#: black
color0                  #0c0c0c
color8                  #393D3F

#: red
color1                  #ff5666
color9                  #B33951

#: green
color2                  #9FC490
color10                 #70AE6E

#: yellow
color3                  #E6C79C
color11                 #E2C044

#: blue
color4                  #7180ac
color12                 #5b618a

#: magenta
color5                  #DA4167
color13                 #A4303F

#: cyan
color6                  #99EDCC
color14                 #75BBA7

#: white
color7                  #D5C5C8
color15                 #F7F0F5


#: kitty window border colors and terminal bell colors

active_border_color             #777777
inactive_border_color           #323738
bell_border_color               #e97e57


#: Tab bar colors

active_tab_foreground           #FAC748
active_tab_background           #0c0c0c
inactive_tab_foreground         #d5c5c8
inactive_tab_background         #393D3F
