#!/usr/bin/env bash

mkdir -p ~/Pictures/screenshots
grim -t png ~/Pictures/screenshots/$(date +%s).png
# dunstify -r 3101 'Screenshot taken'
notify-send.sh --replace-file=/tmp/shotnotif -u normal "Screenshot Taken"
