#!/usr/bin/env bash

# See README.md for usage instructions
bar_color="#d8caac"
volume_step=5
brightness_step=5

# Uses regex to get volume from pactl
function get_volume {
    pamixer --get-volume
}

# Uses regex to get mute status from pactl
function get_mute {
    pactl get-sink-mute @DEFAULT_SINK@ | grep -Po '(?<=Mute: )(yes|no)'
}

# Uses regex to get brightness from xbacklight
function get_brightness {
    light -G
}

# Returns a mute icon, a volume-low icon, or a volume-high icon, depending on the volume
function get_volume_icon {
    volume=$(get_volume)
    mute=$(get_mute)
    if [ "$volume" -eq 0 ] || [ "$mute" == "yes" ]; then
        echo "󰸈"
    elif [ "$volume" -lt 50 ]; then
        echo ""
    else
        echo ""
    fi
}

# Always returns the same icon - I couldn't get the brightness-low icon to work with fontawesome
function get_brightness_icon {
    brightness_icon=""
}

# Displays a volume notification using dunstify
function show_volume_notif {
    volume=$(get_volume)
    volume_icon=$(get_volume_icon)
    notify-send.sh --replace-file=/tmp/volumenotification -u normal "$volume_icon  $volume%" -h int:value:$volume -h string:hlcolor:$bar_color
}

# Displays a brightness notification using dunstify
function show_brightness_notif {
    brightness=`get_brightness`
    get_brightness_icon
    # dunstify -t 1000 -r 2593 -u normal "$brightness_icon  $brightness%" -h int:value:$brightness -h string:hlcolor:$bar_color
    bright=${brightness%.*}
    notify-send.sh --replace-file=/tmp/brightnessnotification -u normal "$brightness_icon  $brightness%" -h int:value:$bright -h string:hlcolor:$bar_color
}

# Main function - Takes user input, "volume_up", "volume_down", "brightness_up", or "brightness_down"
case $1 in
    volume_up)
    # Unmutes and increases volume, then displays the notification
    pactl set-sink-mute @DEFAULT_SINK@ 0
    pactl set-sink-volume @DEFAULT_SINK@ +$volume_step%
    show_volume_notif
    ;;

    volume_down)
    # Raises volume and displays the notification
    pactl set-sink-volume @DEFAULT_SINK@ -$volume_step%
    show_volume_notif
    ;;

    volume_mute)
    # Toggles mute and displays the notification
    pactl set-sink-mute @DEFAULT_SINK@ toggle
    show_volume_notif
    ;;

    brightness_up)
    # Increases brightness and displays the notification
    sudo light -A $brightness_step
    show_brightness_notif
    ;;

    brightness_down)
    # Decreases brightness and displays the notification
    sudo light -U $brightness_step
    show_brightness_notif
    ;;
esac
