#!/usr/bin/env bash

mic(){
	inp=`pamixer --list-sources | awk '/alsa_input/ {printf $1}'`
	mic=`pamixer --source $inp --get-volume-human`
	if [[ "$mic" == "muted" ]]; then
		dunstify -r 3101 "Mic has been unmuted";
		pamixer --source $inp -t
		sleep 2;
		dunstctl close-all;
	else
		pamixer --source $inp -t
		dunstify -r 3101 "Mic has been muted";
		sleep 2;
		dunstctl close-all;
	fi
}

mic
