#!/usr/bin/env bash

mic(){
	inp=`pamixer --list-sources | awk '/alsa_input/ {printf $1}'`
	mic=`pamixer --source $inp --get-volume-human`
	if [[ "$mic" == "muted" ]]; then
		dunstify -r 3101 "Mic has been unmuted" -t 1000;
		pamixer --source $inp -t
	else
		pamixer --source $inp -t
		dunstify -r 3101 "Mic has been muted" -t 1000;
	fi
}

mic
