#!/bin/bash

# CREATING WORKING DIRECTORY
# mkdir -p ~/.image 

# TAKING AND BLURRING SCREENSHOT

# grim -t png ~/.image/image.png
# convert ~/.image/image.png -channel RGBA -blur 0x8 ~/.image/image_blurred.png

# LOCKING SCREEN
# swaylock -C ~/.config/swaylock/swaylock.conf
swaylock -c 00000000

# CLEANING UP
# rm -rf ~/.image/image.png
# rm -rf ~/.image/image_blurred.png
