-- Auto-generated by DMS — do not edit manually

hl.monitor({ output = "eDP-1", mode = "1920x1080@59.999", position = "2048x288", scale = 1.25, vrr = 0, bitdepth = 10, cm = "adobe" })
hl.monitor({ output = "DP-1", mode = "2560x1440@59.951", position = "0x0", scale = 1.25, bitdepth = 10, cm = "wide", sdrbrightness = 2, sdrsaturation = 1.5 })
